name = "aiken-lang/aiken_merkle_tree"
version = "0.0.0"
license = "Apache-2.0"
description = "Aiken contracts for project 'aiken-lang/aiken-merkle-tree'"

[repository]
user = "aiken-lang"
project = "aiken_merkle_tree"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.7.0"
source = "github"
